### ISSUE TITLE
[Desktop] Copy Break

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#66]
Should **We'll** fall on the next line @scottiedarko 

<img width="1552" alt="Screen Shot 2020-06-15 at 7 05 50 PM" src="https://user-images.githubusercontent.com/58711192/84724001-dd5cd000-af3b-11ea-8364-080fadbe0ce7.png">

**Comment by friedman74** [comment]
would be nice if it doesn't cause other responsiveness issues

**Comment by zerostyle** [comment]
Can do, but I will need to reduce the size of the text. Otherwise we will get clipping, or text broken on three lines.

**Comment by scottiedarko** [comment]
Hmm my headline here says "Enter to win' instead of "If You win, We'll Let You Know" ?  Am I cached? The headline/button and the social text/icons could move down in my view version as well.


![enterToWin](https://user-images.githubusercontent.com/20975193/84809738-39b50380-afbf-11ea-8174-bff7dc8427cd.jpg)

**Comment by zerostyle** [comment]
@scottiedarko That is the copy for duplicate email. The copy you are mentioning is for the a successful submission.

**Comment by zerostyle** [comment]
Should I reduce the headline size to make the suggested line break fit?

**Comment by scottiedarko** [comment]
yes lets try that, i think 2 lines is a big deal to them.
